fix: `.ident` hover in patterns
leanprover/lean4 pull request #1664
Opened 2022-09-29 08:23 UTC by digama0

This is the result of many hours of debugging. When you use `| .succ x =>` in a pattern, it was not giving the hover for constant `Nat.succ`, only the whole term `Nat.succ x`. If you write `| Nat.succ x` however you do get the hover for the constant. The reason is because the termInfo for `Nat.succ` is added during `collectPatternVars`, but this is too early for dotted identifiers and they are only resolved once we enter the pattern. But once `isPattern` is true, we discard generated termInfos and replace them with a `patternRef` expr annotation.

Normally that would be okay because these annotations are later unpacked after the dependent match eliminator has done its job, but it turns out that for the constructor head itself it will clobber `patternRef` annotations. Plus, even if it did preserve them we aren't really interested in the post-match-elimination expression here, we want to record the data early like is done for plain identifiers.

The solution is simple: override the `isPattern` suppression for this particular termInfo, since we want it to act like it was done before we entered the pattern.

2022-09-29 13:05 UTC, Kha approved these changes
I don't have the pattern elaboration in my working memory, but going from your description the change sounds reasonable

2022-09-29 18:37 UTC, leodemoura commented
I want to review this PR before merging.
I am assigning myself as a reviewer.

2022-09-30 16:15 UTC, leodemoura commented on src/Lean/Elab/Term.lean
> +def addTermInfo (stx : Syntax) (e : Expr) (expectedType? : Option Expr := none) (lctx? : Option LocalContext := none) (elaborator := Name.anonymous) (isBinder := false) (force := false) : TermElabM E
Could you please add a docstring and document `force`?

2022-09-30 16:21 UTC, leodemoura requested changes
Document `force` in docstring at `addTermInfo`. Could you please also add note describing why it was added and a reference to this PR?

2022-09-30 18:16 UTC, leodemoura commented
Thanks for the changes. I will merge as soon as the conflicts above have been addressed.

2022-09-30 18:17 UTC, leodemoura approved these changes

2022-09-30 22:18 UTC, merged