test: add lake benchmarks
leanprover/lean4 pull request #2457
Opened 2023-08-24 14:14 UTC by tydeu

@Kha Hopefully I configured this right.

2023-08-24 14:15 UTC, tydeu commented
!bench

2023-08-24 20:48 UTC, tydeu commented
!bench

2023-08-24 21:11 UTC, tydeu commented
!bench

2023-08-24 21:36 UTC, tydeu commented
!bench

2023-08-25 01:08 UTC, tydeu commented
@Kha Any suggestion for improvements? Two potential uncovered test cases I thought of:

1. Multi-package elaboration
2. Modules with actual code

Case (2) could be reasonably addressed by benchmarking a build of the Lean core itself. However, I am not sure either of these cases would provide significantly different benchmarks to be worth the added complexity.

2023-08-26 04:45 UTC, tydeu commented
I liked the benchmarks from #2463, so I went ahead and merged them into here.

2023-08-26 04:48 UTC, tydeu commented
!bench

2023-08-26 05:14 UTC, tydeu commented
Interesting, it appears a no-op build of Lean is faster than I no-op build of the inundation dummy project. So I guess number of files to hash is more significant than the contents of them?

2023-08-26 08:31 UTC, Kha requested changes
> Modules with actual code

Why is that interesting? We want to benchmark Lake, not Lean. A synthetic benchmark is great, it ensures that the input stays constant and cannot influence the timings.

2023-08-26 09:13 UTC, Kha commented
> Modules with actual code

Ah, I suppose it is interesting e.g. in the context of #2444. I think I would still value isolated tests over that. It's okay to do benchmarks like this one manually if we don't expect output size to matter anymore after this change.

2023-08-27 01:50 UTC, tydeu commented
@Kha Sime other interesting points of the Lean builds and real code builds:

 * Provides a time comparison with another build system (CMake/Make) -- we can officially say that, in parallel, Lake is faster than Make even for a complex project.

 * Enables measuring of code-level finer-grain dependency specification (like the forthcoming module system or leanprover/lake#86).

 * Similarly, things like asynchronous proof checking could also be captured by such a benchmark (if these are integrated with Lake enough to enable it to move onto building downstream files while the proofs are still being checked).

However, I am happy to remove the benchmark if you are confident it is not worth it. I was also initially unsure whether it was good idea.

2023-08-30 19:57 UTC, tydeu commented
!bench

2023-08-30 23:03 UTC, tydeu commented
!bench

2023-08-30 23:40 UTC, tydeu commented
!bench

2023-09-01 18:58 UTC, tydeu commented
!bench

2023-09-04 09:35 UTC, Kha commented on tests/bench/inundation/README.md
> +The the modules lack any code.
```suggestion
The modules lack any code.

```

2023-09-07 02:06 UTC, tydeu commented
> In any case, I'm still not convinced this is worth increasing the benchmark run time by 50%, no.

It may be worth noting that the Lean build itself is only contributing 4-5 minutes (so about 25% of the overall time), the other parts contribute about 1-3 minutes and benchmark without these changes is already usually 13-14 minutes. However, I presume that means you prefer me to take it out, so I will do that soon.

2023-09-07 07:38 UTC, Kha commented
> It may be worth noting that the Lean build itself is only contributing 4-5 minutes (so about 25% of the overall time), the other parts contribute about 1-3 minutes and benchmark without these changes is already usually 13-14 minutes

I'm not sure what you are trying to tell me with that. All I see is a total increase from 13 minutes to 20 minutes.

2023-09-22 18:05 UTC, merged