feat: string gaps for splitting string literals across multiple strings
leanprover/lean4 pull request #2821
Opened 2023-11-05 03:32 UTC by kmill

(Writing an RFC here in this PR while it is a draft.)

Implements [Haskell-style](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-200002.6) "gaps" in string literals. These are escape sequences of the form `"\" whitespace+ "\"` that have the interpretation of an empty string. For example,
```
  "this is\
  \ a string"
```
is equivalent to `"this is a string"`.

**Rationale.** In projects that have a line length limit (such as std and mathlib), long strings need to be wrapped to respect this limit. A workaround one sees is using string interpolation with the empty string, since the expression between curly braces may itself contain whitespace that is ignored:
```
  s!"this is{
  ""} a string"
```
However, this term produces `"this is" ++ "" ++ " a string"`, which is not an atomic string literal. Note that users do not write
```
  "this is
   a string"
```
because this includes extraneous whitespace in the string. This particular example is `"this is\n   a string"`.

**Caveats.**
1. Note that the whitespace in a string gap must be whitespace. Comments are not permitted. The parser does not interpret string literals (that is, it does not do escape sequence replacements), and they are instead interpreted during elaboration time. If the gaps were to admit comments, this interpretation process would need to be able to handle comment syntax. This limitation is also found in the Haskell 2010 language specification.

2. There is a slight overlap with `"\\"` escapes for backslashes. The difference between the two is that gaps must have at least one character of whitespace between the backslashes. In practice, one would never write `\\` and expect it to be a gap since the point is for it to span multiple lines.

3. The implementation needs to be careful not to allow string gaps inside character literals. String literals and character literals share code for handling escapes, but the string gap feature only makes sense for strings.

**Other designs for multiline strings include:**
- Trying to adapt C's automatic string concatenation, where the juxtaposition `"this is" " a string"` is equivalent to the concatenated version. However, this creates an ambiguity when passing strings as arguments to functions.
- Allowing interpolated strings to include expression-free `{}` notation
  ```
  s!"this is{
    } a string"
  ```
  However, this forces users to switch to using an interpolated string if they want a multiline string literal.
- Allowing a `\` at the end of a line to mean string continuation. For example
  ```
      "this is\
   a string"
  ```
  However, such continuations would not respect indentation since any whitespace at the start of the next line would be included. Furthermore, there is the small question of `\r\n` vs `\n` for the line ending.

**There is no need to reinvent lexical syntax for multiline string literals.** The Haskell solution satisfactorily solves the problem of long strings that need to be wrapped over multiple lines. There are no downsides to adding gaps to Lean's lexical syntax, and the feature has a simple implementation.

2023-12-05 09:09 UTC, Kha requested changes

2023-12-05 09:09 UTC, Kha commented on tests/lean/string_gaps.lean
> +import Lean
Please minimize the import and add docstrings https://lean-lang.org/lean4/doc/dev/testing.html#writing-good-tests

2023-12-06 17:08 UTC, kmill commented
@Kha What are you looking for with the changelog entry? Do you mean I should write something in `RELEASES.md` for the development version?

By the way, once the string literal PRs are all sorted out, I can write a rough draft of the strings section of the reference manual.

2023-12-06 17:59 UTC, Kha commented
> Do you mean I should write something in `RELEASES.md` for the development version?

Yes, a brief sentence similar to the PR title and a PR link are sufficent.

> By the way, once the string literal PRs are all sorted out, I can write a rough draft of the strings section of the reference manual.

Great! You should probably get in touch with @david-christiansen for that.

2023-12-07 09:09 UTC, merged