feat: add BitVec.neg_neg
leanprover/lean4 pull request #4977
Opened 2024-08-10 04:57 UTC by tobiasgrosser

.. as well as neg_neq_iff_neq_neg.

2024-08-10 04:58 UTC, tobiasgrosser commented
Draft PR to indicate that @bollu or @alexkeizer should maybe double-check my style choices before Kim does his review.

2024-08-10 05:42 UTC, tobiasgrosser commented
I am currently still unhappy with the BitVec.neg_neg proof, as the explicit use of Nat.mod_eq_of_lt is something that comes up very often also in other proofs and is always tedious to write:

```lean4
theorem neg_neg {x : BitVec w} : - - x = x := by
  by_cases h : x = 0
  · simp [h]
  · simp only [toNat_eq, ofNat_eq_ofNat, toNat_ofNat, Nat.zero_mod] at h
    simp only [toNat_eq, toNat_neg]
    rw [Nat.mod_eq_of_lt (a := 2 ^ w - x.toNat) (by omega)]
    rw [Nat.mod_eq_of_lt (by omega)]
    omega
```

2024-08-10 05:59 UTC, tobiasgrosser commented
I found a neat way to clean this up with two helper theorems `sub_toNat_mod_cancel` and `sub_sub_toNat_cancel`.

2024-08-11 09:04 UTC, tobiasgrosser commented
This is now clean from my perspective and ready to review.

2024-08-11 09:48 UTC, hargoniX requested changes

2024-08-11 09:48 UTC, hargoniX commented on src/Init/Data/BitVec/Lemmas.lean
> +  simp [bv_toNat] at h
Non terminal `simp`.

2024-08-11 09:48 UTC, hargoniX commented on src/Init/Data/BitVec/Lemmas.lean
> +    <;> simp [BitVec.neg_neg] at h
```suggestion
theorem neg_ne_iff_ne_neg {x y : BitVec w} : -x ≠ y ↔ x ≠ -y := by
  constructor
  all_goals
    intro h h'
    subst h'
    simp at h
```

2024-08-11 09:50 UTC, tobiasgrosser commented on src/Init/Data/BitVec/Lemmas.lean
> +  simp [bv_toNat] at h
Addressed.

2024-08-11 09:53 UTC, hargoniX approved these changes

2024-08-12 00:54 UTC, merged