feat: use libuv for tempfiles
leanprover/lean4 pull request #5135
Opened 2024-08-22 13:27 UTC by hargoniX

This is currently broken because of linker issues. CC @TwoFX

2024-10-01 08:41 UTC, TwoFX commented
I would appreciate if @Kha could sign off on these rather invasive changes.

2024-10-07 15:18 UTC, Kha requested changes

2024-10-07 15:18 UTC, Kha commented on src/CMakeLists.txt
> +  string(APPEND LEAN_EXE_LINKER_FLAGS " ${LIB}/temp/libleanshell.a ${TOOLCHAIN_STATIC_LINKER_FLAGS} ${EMSCRIPTEN_SETTINGS} -lnodefs.js -s EXIT_RUNTIME=1 -s MAIN_MODULE=1 -s LINKABLE=1 -s EXPORT_ALL=1
needs comment

2024-10-07 16:00 UTC, TwoFX commented on script/prepare-llvm-linux.sh
> +$CP $GLIBC/lib/libpthread_nonshared.a stage1/lib/glibc
This is needed if you use the pthreads function `pthread_atfork` (only then - there is literally only one symbol in that library. As far as I can tell, Lean itself doesn't need this function, but LibUV does.

2024-10-07 16:03 UTC, TwoFX commented on src/CMakeLists.txt
> +  string(APPEND LEAN_EXE_LINKER_FLAGS " ${LIB}/temp/libleanshell.a ${TOOLCHAIN_STATIC_LINKER_FLAGS} ${EMSCRIPTEN_SETTINGS} -lnodefs.js -s EXIT_RUNTIME=1 -s MAIN_MODULE=1 -s LINKABLE=1 -s EXPORT_ALL=1
Done

2024-10-08 08:03 UTC, Kha commented on script/prepare-llvm-linux.sh
> +$CP $GLIBC/lib/libpthread_nonshared.a stage1/lib/glibc
Interesting. Let's document this as well?

2024-10-08 08:03 UTC, Kha approved these changes

2024-10-14 12:54 UTC, TwoFX commented on script/prepare-llvm-linux.sh
> +$CP $GLIBC/lib/libpthread_nonshared.a stage1/lib/glibc
Done.

2024-10-14 14:22 UTC, merged

2025-02-24 23:40 UTC, eric-wieser commented on src/runtime/io.cpp
> +        object_ref pair = mk_cnstr(0, io_wrap_handle(handle), mk_string(req.path));
This leaks the memory within `req`; see #7151 for a fix