fix: when building cadical set cmake COPY_CADICAL to determine whether to copy it
leanprover/lean4 pull request #5931
Opened 2024-11-03 10:03 UTC by juhp

This prevents `cadical` getting "installed" (copied) when it was already available in the system.

Closes: #5603

2024-11-03 10:33 UTC, juhp commented
Results:

```shellsession
$ elan run leanprover/lean4-pr-releases:pr-release-5930 cadical --version
1.9.5
$ elan toolchain install leanprover/lean4-pr-releases:pr-release-5931
:
$ elan run leanprover/lean4-pr-releases:pr-release-5931 cadical --version
2.0.0
$ rpm -q cadical
cadical-2.0.0-3.fc41.x86_64
```

So the Linux toolchain does not build cadical in github?

2024-11-03 10:34 UTC, juhp commented
Should I try with mathlib?

2024-11-03 10:47 UTC, juhp commented
Well it certainly gets rid of cadical, lol - not sure if this is working correctly, hm

2024-11-03 11:18 UTC, juhp commented
Okay now reworked to be a cmake option (`ON` by default) - description updated

2024-11-03 11:28 UTC, juhp commented
Okay cadical seems back in `List Install Tree` so I think this is okay now.

2024-11-04 11:11 UTC, juhp commented
(Well I can't help feeling that strictly speaking `OFF` seems the correct default, but then of course it should be set to `ON` in github actions, etc. Anyway this is a step forward at least.)

2024-11-05 10:40 UTC, Kha requested changes

2024-11-05 10:40 UTC, Kha commented on src/CMakeLists.txt
> +option(COPY_CADICAL "Install a copy of cadical" ON)
This is not a dev-specifc option, please put it below `INSTALL_LICENSE`. `INSTALL_CADICAL` would likely be a more appropriate name then.

2024-11-27 13:47 UTC, merged