feat: BitVec.signExtend.{toNat, toInt}
leanprover/lean4 pull request #6038
Opened 2024-11-11 18:06 UTC by mhk119

This PR adds toNat and toInt theorems for BitVec.signExtend.

2024-11-16 17:07 UTC, hargoniX requested changes
Some minor remarks, I got two additional ones:
1. Could you rebase your branch on leanprover master? The test task IO flipper should be gone there.
2. Did you check that your theorem statements are in simp normal form?

2024-11-16 17:07 UTC, hargoniX commented on src/Init/Data/BitVec/Lemmas.lean
> +  · simp [hx, Nat.testBit_mul_pow_two_add _ x.isLt, testBit_toNat]
Not in simp normal form.

2024-11-16 17:07 UTC, hargoniX commented on src/Init/Data/BitVec/Lemmas.lean
> +  · simp [hx, Nat.testBit_mul_pow_two_add _ x.isLt, testBit_toNat]
Not in simp normal form.

2024-11-16 17:07 UTC, hargoniX commented on src/Init/Data/BitVec/Lemmas.lean
> +  have ⟨k, hk⟩ := Nat.exists_eq_add_of_le hv; rw [hk]
A `have` followed by `; tac` where the proof continues further down feels a bit weird, maybe put the `rw` on the next line.

2024-11-19 20:17 UTC, mhk119 commented on src/Init/Data/BitVec/Lemmas.lean
> +  · simp [hx, Nat.testBit_mul_pow_two_add _ x.isLt, testBit_toNat]
Do you mean non-terminal simps?

2024-11-20 09:04 UTC, hargoniX commented on src/Init/Data/BitVec/Lemmas.lean
> +  · simp [hx, Nat.testBit_mul_pow_two_add _ x.isLt, testBit_toNat]
Yes.

2024-11-29 15:18 UTC, hargoniX commented
The PR now just seems to consist of a change to code that is fine according to the style guide? What is the motivation here?

2024-12-01 22:09 UTC, mhk119 commented
> The PR now just seems to consist of a change to code that is fine according to the style guide? What is the motivation here?

My bad, I didn't see that the theorems got merged into main in the meantime. Closing this :).

2024-12-01 22:09 UTC, closed without merging

2024-12-01 22:15 UTC, tobiasgrosser commented
It seems these got added in https://github.com/leanprover/lean4/pull/6155 and https://github.com/leanprover/lean4/pull/6157. In the future, we should cross-reference commits when someone decides to split them. Thank you @mhk119 for getting this in.