Emacs mode lake
leanprover/lean4 pull request #865
Opened 2021-12-10 23:10 UTC by lecopivo

2021-12-11 08:17 UTC, Kha commented
Thanks. Could you add the keyboard shortcut to `lean4-mode/README.md`?

2021-12-11 08:18 UTC, Kha commented on lean4-mode/lean4-lake.el
> +      (compile "lake build"))))
You should probably use `(lean4-get-executable "lake")` here

2021-12-11 12:12 UTC, lecopivo commented
Sure, I fix that. I will also add ability to run `lake run <script>`. Would something else make sense?

2021-12-14 02:08 UTC, tydeu commented
@lecopivo

> I will also add ability to run `lake run <script>`.

Fyi, I plan to change this to `lake script run <script>` soon, so maybe hold off on that for just a little while?

2021-12-14 08:22 UTC, lecopivo commented
Sure, I can wait. 

Also, is there a planned support for unit testing in lake? Or is that ment to be done through scripts?

2021-12-14 08:28 UTC, tydeu commented
@lecopivo 

> Also, is there a planned support for unit testing in lake? Or is that ment to be done through scripts?

Yeah, testing will probably be done through a combination of a separate testing library, a test runner executable, and a script (like how [mocha](https://mochajs.org/) is generally used in JavaScript).

2021-12-15 12:08 UTC, Kha commented
You should use `lake env` (if there is a lakefile) for running `lean` with `LEAN_PATH` set up correctly.

2021-12-15 12:16 UTC, lecopivo commented
> You should use `lake env` (if there is a lakefile) for running `lean` with `LEAN_PATH` set up correctly.

Ohh I didn't about this, well at least I got some practice with elisp after a long time.

2021-12-15 12:24 UTC, lecopivo commented
Concerning keybindings, I'm not the biggest fan of the `C-c C-p C-l`. I picked it to be consistent with keybindings for leanpkg. What about having `C-c C-x` to be `lean4-std-exe` and `C-c C-l` be `lean4-lake-build`. Alternatively, we can use `C-c C-b` for `lean4-lake-build` as `lean4-message-boxes-toggle` does no longer exist.

2021-12-15 13:48 UTC, Kha commented
Either would be fine with me.

2021-12-15 16:24 UTC, lecopivo commented
I will go for `C-c C-l` for `lean4-lake-build`. I will add an option to rebuild lake project before running `lean4-std-exe`.

2021-12-15 18:19 UTC, Kha commented
I don't have a strong opinion on any of these since I never use them :) . But rebuilding might be problematic if some downstream module fails to build. Ideally we would only rebuild the imports like the server does via `lake print-paths`, but that's a bit more complicated.

2022-01-19 11:30 UTC, Kha requested changes
> You should use `lake env` (if there is a lakefile) for running `lean` with `LEAN_PATH` set up correctly.

This is still missing I think

2022-01-19 11:41 UTC, lecopivo commented
Yes it is still missing. I will try to fix that and change the keybindings sometime this week. In the current form it solves my problem :) so I had priorities elsewhere.

2022-02-14 16:00 UTC, closed without merging